{% set version = "6.0" %}

package:
  name: pyyaml
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/PyYAML/PyYAML-{{ version }}.tar.gz
  sha256: 68fb519c14306fec9720a2a5b45bc9f0c8d1b9c72adf45c37baedfcd949c35a2
  patches:
    - 0001-Ensure-we-do-not-end-up-wih-CRLF-line-endings-on-tes.patch

build:
  number: 1
  skip: True  # [py<36]
  script:
    - python setup.py --with-libyaml build_ext --include-dirs="${PREFIX}/include" --library-dirs="${PREFIX}/lib"  # [unix]
    - python setup.py --with-libyaml build_ext --include-dirs="%LIBRARY_INC%" --library-dirs="%LIBRARY_LIB%"      # [win]
    - python setup.py install
    - python setup.py test

requirements:
  build:
    - {{ compiler('c') }}
    - patch  # [now win]
    - m2-patch  # [win]
  host:
    - python
    - cython
    - setuptools
    - wheel
    - yaml
  run:
    - python
    - yaml

test:
  imports:
    - yaml
    - _yaml   # [python_impl == "cpython"]
  requires:
    - pip
  commands:
    # temporarily skipping pip check on win and pypy build because of bizarre tqdm issue
    - pip check  # [not (win and python_impl == 'pypy')]

about:
  home: http://pyyaml.org/wiki/PyYAML
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: YAML parser and emitter for Python
  description: |
    YAML is a data serialization format designed for human readability and interaction with
    scripting languages.
  doc_url: http://pyyaml.org/wiki/PyYAMLDocumentation
  doc_source_url: http://pyyaml.org/browser/pyyaml/trunk/README
  dev_url: https://github.com/yaml/pyyaml

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - pelson
    - ocefpaf
