{% set version = "5.4.1" %}

package:
  name: pyyaml
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/PyYAML/PyYAML-{{ version }}.tar.gz
  sha256: 607774cbba28732bfa802b54baa7484215f530991055bb562efbed5b2f20a45e
  patches:
    - 0001-Ensure-we-do-not-end-up-wih-CRLF-line-endings-on-tes.patch

build:
  number: 0
  skip: True  # [py<36]
  script:
    - >-
        "{{ PYTHON }}" -m pip install .
        --global-option="--with-libyaml"
        --global-option="build_ext"
        --global-option="-I${PREFIX}/include"  # [unix]
        --global-option="-L${PREFIX}/lib"      # [unix]
        --global-option="-I%LIBRARY_INC%"      # [win]
        --global-option="-L%LIBRARY_LIB%"      # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - m2-patch  # [win]
    - patch  # [not win]
  host:
    - python
    - cython
    - setuptools
    - pip
    - wheel
    - yaml
  run:
    - python
    - yaml

test:
  imports:
    - yaml
    - _yaml   # [python_impl == "cpython"]
  requires:
    - pip
  commands:
    # temporarily skipping pip check on win and pypy build because of bizarre tqdm issue
    - pip check  # [not (win and python_impl == 'pypy')]

about:
  home: http://pyyaml.org/wiki/PyYAML
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: YAML parser and emitter for Python
  description: |
    YAML is a data serialization format designed for human readability and interaction with
    scripting languages.
  doc_url: http://pyyaml.org/wiki/PyYAMLDocumentation
  doc_source_url: http://pyyaml.org/browser/pyyaml/trunk/README
  dev_url: https://github.com/yaml/pyyaml

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - pelson
    - ocefpaf
