{% set version = "3.12" %}


package:
  name: pyyaml
  version: {{ version }}

source:
  fn: PyYAML-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/P/PyYAML/PyYAML-{{ version }}.tar.gz
  sha256: 592766c6303207a20efc445587778322d7f73b161bd994f227adaa341ba212ab

build:
  number: 0
  script:
    - python setup.py --with-libyaml build_ext --include-dirs="${PREFIX}/include" --library-dirs="${PREFIX}/lib"  # [unix]
    - python setup.py --with-libyaml build_ext --include-dirs="%LIBRARY_INC%" --library-dirs="%LIBRARY_LIB%"      # [win]
    - python setup.py install
    - python setup.py test

requirements:
  build:
    - python
    - yaml

  run:
    - python
    - yaml

test:
  imports:
    - yaml
    - _yaml

about:
  home: http://pyyaml.org/wiki/PyYAML
  license: MIT
  summary: YAML parser and emitter for Python

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
