travis:
  secure:
    BINSTAR_TOKEN: KASM9hjbkfGtvGW4Ds4dNwXDWiAuiZIebw4WYSAKeAyETxExP6tJK+p4w9XtcK0Nd0Ifw2lrJqFsdSGaHG2GxSDdELenCrZ9sr6B+/f6VAtY//H60ezYNKbUUDkw3Zar0V75j9ZE2+wHIQeBr/N1qHvE35DhzkjHECCLLrHSHB/BIpmA64CT7stXrmWZ8+FHq2ZSxqH++lbcUkNUS9tZqKm3BtsDSDlRNj56YyKAD/SK4JPZEaSuqWfEfux0qVSi29wdh9AtoCRpV66GpPTzJGG83E2HXGNDn3VuKJ0bSxdOxu9Gzbn3W0A3hyoOHBWzYFpEaseKGR8/pmtvDo20BDfzd7cXuHyLeKf4v0p9q5QFuzTmKOs5xqIt4Kvp33GLucjuMWPdh7Bj0hgdk1Kd0ToJCTItnbpWwz/5Qf6KkomYVHUI6CG9qZPdcFPJNxSWbGxZft0h6VWYOENg5mi7Cjsr4WZfG1QQPaCCWN1Wd/D401t203o7/JeOGHGv+ozIVYzd6xMjhDWdcQ66gASRp54J/VSFnGZ+DLdeO5hhxDQ4m5xbTWWcPlIIKjUG4Mv23j7qkDEC3vNkktQQ9sbrPuB4uE6qth6TqxR2VKPpCB6rBAsV1AziULyW0kWHce839edIz6bGfDF8u++ACUXwR4X4LpVoDBOfhDm7KqhKqUE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
